
default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host:  <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: project_manager_development

test:
  <<: *default
  database: project_manager_test

production:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>
