GET http://localhost:3000/api/projects/26/activities
Content-Type: application/json
Accept: application/json

###

POST http://localhost:3000/api/projects/26/activities
Content-Type: application/json
Accept: application/json

{
  "name": "ASdasd",
  "start_date": "2020-10-30T17:40:55.351Z",
  "end_date": "2021-11-04"
}

###

PUT http://localhost:3000/api/projects/325/activities/251
Content-Type: application/json
Accept: application/json

{
  "finished": true
}
